main: main.cpp PaqueteDatagrama.o
	g++ main.cpp PaqueteDatagrama.o -o main.out
SocketDatagrama: SocketDatagrama.cpp PaqueteDatagrama.o
	g++ SocketDatagrama.cpp -c
PaqueteDatagrama: PaqueteDatagrama.cpp
	g++ PaqueteDatagrama.cpp -c