all: 7_2 morris calculosC calculosJ
7_2: 7_2.cpp
	g++ 7_2.cpp -o 7_2.out
morris: morris.c
	gcc morris.c -o morris.out
calculosC: calculos.cpp
	g++ calculos.cpp -o calculos.out
calculosJ: calculos.java
	javac calculos.java