#programa2_2: programa2_2.cpp Fecha.o
#	g++ programa2_2.cpp Fecha.o -o programa2_2
#programa2_3: programa2_3.cpp Fecha.o
#	g++ programa2_3.cpp Fecha.o -o programa2_3
programa2_4: programa2_4.cpp Fecha.o
	g++ programa2_4.cpp Fecha.o -o programa2_4
Fecha.o: Fecha.cpp Fecha.h
	g++ Fecha.cpp -c
