all: programa13-1 programa13-2 codInternet1 codInternet2
 
programa13-1: programa13-1.c
	gcc programa13-1.c -o programa13-1.out
programa13-2: programa13-2.c
	gcc programa13-2.c -o programa13-2.out

codInternet1: codInternet1.c
	gcc codInternet1.c -o codInternet1.out

codInternet2: codInternet2.c
	gcc codInternet2.c -o codInternet2.out 